### ISSUE TITLE
Where can I find pd 0.51-0

### ISSUE THREAD

**Issue by vjx** [porres/Live-Electronics-Tutorial#21]
The Readme file says it need pd 0.51.0 or later but the last version I can find on puredata.info is pd 0.50.0 Where can I get the latest version?
Thanks

**Comment by porres** [comment]
you can't because it's not out yet :) this is for the next update/release

but go to current releases https://github.com/porres/Live-Electronics-Tutorial/releases

and note you can get the latest tutorial release directly from Pd (Help => Find externals)
