### ISSUE TITLE
Colon in directory name breaks clone on Windows

### ISSUE THREAD

**Issue by csestili** [porres/Live-Electronics-Tutorial#28]
Hi, thank you for your amazing tutorial!

The directory name `Examples/Vol.2/Part.05-Filters(Basic)/22-Filters.types/2.Filter.Types/1.Low:High-Pass` contains a colon, and this causes `git clone` to fail on Windows:

```
fatal: cannot create directory at 'Examples/Vol.2/Part.05-Filters(Basic)/22-Filters.types/2.Filter.Types/1.Low:High-Pass': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Workaround: I downloaded the repo contents as .zip, changed that folder name to 1.Low-High-Pass before extracting, and then extracted. This seems to have worked.

Would you mind changing this directory name to one that would work on Windows? Feel free to ask me to test for you.

Thank you!

**Comment by porres** [comment]
h, i dont see a colon, I have a slash "1.Low/High-Pass"

**Comment by csestili** [comment]
Here's what I see in my browser:
![tmp](https://user-images.githubusercontent.com/10887466/101938166-c0762200-3b97-11eb-8743-d1d12b624b30.PNG)

And from the .zip archive, in 7zip:
![tmp2](https://user-images.githubusercontent.com/10887466/101938737-bacd0c00-3b98-11eb-901c-588b7f80947a.PNG)

However, slashes are also disallowed in filenames on Windows ([source](https://gist.github.com/doctaphred/d01d05291546186941e1b7ddc02034d3). I wonder whether git/github converts the slash into a colon to attempt to avoid path issues?

**Comment by porres** [comment]
what happens when you download the ELSE library from deken? This tutorial is a part of the ELSE library and this is just a separate repository, but not an independent one.

**Comment by porres** [comment]
pleas respond, otherwise i'll have to close this issue

**Comment by csestili** [comment]
Hi, I apologize for not responding sooner. I was able to install the ELSE library as an external in Pd and use it with no issues.
