### ISSUE TITLE
/Vol.1/Part.04-Synthesis(Basic)/20-Waveshaping/6.Chebyshev.polinomials error with loop 1024

### ISSUE THREAD

**Issue by muziker** [porres/Live-Electronics-Tutorial#32]
When trying this, i've been getting
loop: number of iterations need to be >= 1

In the top [else/loop 1024], if [1024 ( -> [else/loop 1024 ] is added instead, then the example works. It's probably not what is expected, but it allows the example to run.

**Comment by porres** [comment]
I guess I already fixed that recently but it's not available as a release yet. Try the last state from this repository
