### ISSUE TITLE
Missing part of sentence?

### ISSUE THREAD

**Issue by chkworks** [porres/Live-Electronics-Tutorial#52]
Is there some part of the sentence missing? It just end with "You can use dollar"
Seen in Pd Quickstart>Syntax>Basic Syntax>Dollar Signs In Messages

<img width="500" alt="Bildschirmfoto 2023-02-04 um 13 17 58" src="https://user-images.githubusercontent.com/5701406/216767270-406e1514-6007-4dff-be3f-cadbd917393b.png">

**Comment by chkworks** [comment]
<img width="152" alt="Bildschirmfoto 2023-02-04 um 13 21 10" src="https://user-images.githubusercontent.com/5701406/216767386-79c1924c-6133-4b9e-aa87-d5c22afeb495.png">

Also seems the order of files is a bit off here.

**Comment by chkworks** [comment]
Another missing sentence ending in Pd Quickstart>Syntax>Set>Arrays:

<img width="533" alt="Bildschirmfoto 2023-02-04 um 13 45 33" src="https://user-images.githubusercontent.com/5701406/216768482-ce0a38e9-224c-4c00-a2b9-efce6491dd01.png">

**Comment by porres** [comment]
thanks, keep these coming please
