### ISSUE TITLE
What is bily-in? 

### ISSUE THREAD

**Issue by chkworks** [porres/Live-Electronics-Tutorial#53]
Is this a typo?

Pd Quickstart>Syntax>Set>GUIs Properties

<img width="365" alt="Bildschirmfoto 2023-02-04 um 13 48 47" src="https://user-images.githubusercontent.com/5701406/216768590-87c4f815-4626-44b0-85c6-662a101cfebd.png">

**Comment by porres** [comment]
"built-in"
